import { apiError } from "@/lib/api/error";import { apiSuccess } from "@/lib/api/response";import { database } from "@/lib/database/client";import { relevantNewsRequestSchema } from "@/lib/validation/news";import { authenticateProject } from "@/server/services/request-auth";import { authorizeTopics } from "@/server/services/topics";import { refreshRelevantSources } from "@/server/services/refresh";import { rankRelevantArticles } from "@/server/services/relevance";import { serverEnvironment } from "@/lib/environment/server";
export async function POST(request:Request){
 const started=Date.now(),requestId=crypto.randomUUID();const project=await authenticateProject(request);if(!project)return apiError("UNAUTHORIZED","A valid project API key is required.",401,[],requestId);
 const parsed=relevantNewsRequestSchema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return apiError("VALIDATION_ERROR","The news request is invalid.",400,parsed.error.issues.map(i=>({path:i.path.join("."),message:i.message})),requestId);
 const enabled=await database.projectTopic.findMany({where:{projectId:project.id,status:"ACTIVE",topic:{status:"ACTIVE"}},include:{topic:true}});
 const auth=authorizeTopics(parsed.data.topics.map(t=>t.slug),enabled.map(x=>x.topic.slug));if(auth.unauthorized.length)return apiError("TOPIC_NOT_AUTHORIZED","One or more topics are not enabled for this project.",403,auth.unauthorized.map(slug=>({slug})),requestId);
 const maximum=Math.min(parsed.data.maximumItems??project.maximumItemsPerRequest,project.maximumItemsPerRequest);
 const refresh=await refreshRelevantSources(auth.authorized,project.minimumRefreshIntervalMinutes,project.id);
 const cutoff=new Date(Date.now()-serverEnvironment.NEWS_VISIBLE_HOURS*3_600_000);
 const articles=await database.externalArticle.findMany({where:{status:"ACTIVE",publishedAt:{gte:cutoff},topics:{some:{topic:{slug:{in:auth.authorized}}}}},include:{feedSource:true,topics:{include:{topic:true}}},take:200});
 const ranked=rankRelevantArticles(articles.map(a=>({id:a.id,publishedAt:a.publishedAt,title:a.title,description:a.description??"",topics:a.topics.map(t=>({slug:t.topic.slug,score:t.score,assignmentSource:t.assignmentSource}))})),parsed.data.topics,{excludedTopics:parsed.data.excludedTopics,excludeArticleIds:parsed.data.excludeArticleIds,maximumItems:maximum});
 const byId=new Map(articles.map(a=>[a.id,a]));const items=ranked.map(({article,relevanceScore})=>{const a=byId.get(article.id)!;return{id:a.id,title:a.title,description:a.description,source:{name:a.feedSource.name,websiteUrl:a.feedSource.websiteUrl},originalUrl:a.canonicalUrl,imageUrl:a.imageUrl,publishedAt:a.publishedAt.toISOString(),matchedTopics:a.topics.filter(t=>auth.authorized.includes(t.topic.slug)).map(t=>({slug:t.topic.slug,name:t.topic.name,score:t.score})),relevanceScore}});
 await database.apiRequestLog.create({data:{projectId:project.id,endpoint:"/api/v1/news/relevant",httpMethod:"POST",responseStatus:200,durationMs:Date.now()-started,requestId}});
 return apiSuccess({project:{id:project.id,slug:project.slug,name:project.name},generatedAt:new Date().toISOString(),refresh,items},200,{requestId});
}
