"use client";
import { useState } from "react";
import { PageHeader } from "@/components/dashboard";
import { Panel } from "@/components/ui";
const topics=["Technology","AI & Machine Learning","Finance","Markets","Economy","Politics","Health","Science","Energy","Manufacturing","Retail","Real Estate","Sports","Entertainment"];
export default function FeedsPage(){const [selected,setSelected]=useState(["Technology","AI & Machine Learning","Finance","Markets"]);const [confidence,setConfidence]=useState(80);return <><PageHeader mode="portal" title="Create Custom Feed" description="Build a news feed tailored to your project"/><div className="two-col">
 <div className="page-grid"><Panel title="1. Select Topic"><div style={{padding:15,display:"flex",flexWrap:"wrap",gap:8}}>{topics.map(t=><button key={t} onClick={()=>setSelected(s=>s.includes(t)?s.filter(x=>x!==t):[...s,t])} style={{padding:"7px 10px",fontSize:10,borderRadius:5,color:selected.includes(t)?"#a9ddff":"#acb8c4",border:`1px solid ${selected.includes(t)?"#1377c8":"#293d51"}`,background:selected.includes(t)?"#0a2a49":"#0b1722"}}>{t}</button>)}</div></Panel>
 <Panel title="2. Filters"><div style={{padding:15,display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}><label style={{fontSize:10}}>Countries<select style={control}><option>All Countries</option></select></label><label style={{fontSize:10}}>Language<select style={control}><option>English</option></select></label><label style={{fontSize:10,gridColumn:"1/-1"}}>Minimum Confidence <strong>{confidence}%</strong><input aria-label="Minimum confidence" type="range" min="0" max="100" value={confidence} onChange={e=>setConfidence(+e.target.value)} style={{width:"100%",marginTop:14}}/></label></div></Panel></div>
 <div className="page-grid"><Panel title="3. Relevance Weights"><div style={{padding:15,display:"grid",gap:16}}>{["Breaking News","Industry News","Company News","Market Impact","Regulatory News","Research & Reports"].map((x,i)=><label key={x} style={{display:"grid",gridTemplateColumns:"1fr 1fr 36px",gap:8,fontSize:9,alignItems:"center"}}>{x}<input type="range" aria-label={`${x} weight`} defaultValue={90-i*10}/><span>{90-i*10}%</span></label>)}</div></Panel><Panel title="Feed Preview"><div style={{padding:20}}><div className="muted" style={{fontSize:9}}>Estimated stories / day</div><strong className="display" style={{fontSize:26}}>250 – 400</strong><div style={{marginTop:14,color:"#73e68f",fontSize:11}}>95% estimated relevance</div></div></Panel><button onClick={()=>alert("Feed configuration saved locally for this demonstration.")} style={{border:0,borderRadius:6,padding:11,color:"white",background:"#167fe4",fontWeight:650}}>Save Feed</button></div>
 </div></>}
const control={display:"block",width:"100%",marginTop:7,padding:9,borderRadius:5,border:"1px solid #23384f",background:"#0b1722",color:"#eaf2f8",fontSize:10};
