"use client";
import { useState } from "react";import { PageHeader } from "@/components/dashboard";import { Panel } from "@/components/ui";
type Source={id:string;name:string;feedUrl:string;status:string;feedType:string;minimumRefreshIntervalMinutes:number;lastRefreshAttemptedAt:string|null;lastSuccessfulRefreshAt:string|null;consecutiveFailureCount:number};
export default function SourcesPage(){const[sources,setSources]=useState<Source[]>([]);const[message,setMessage]=useState("Use the private MVP session to manage sources.");const[name,setName]=useState("");const[feedUrl,setFeedUrl]=useState("");
async function load(){const r=await fetch("/api/internal/sources");const j=await r.json();if(!r.ok){setMessage(j.error?.message??"Unable to load sources.");return}setSources(j.data);setMessage(j.data.length?"Sources loaded.":"No feeds have been approved or added.");}
async function action(mode:"add"|"test"){const payload={name,slug:name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,""),feedUrl,feedType:"auto",minimumRefreshIntervalMinutes:30,topicSlugs:[],...(mode==="test"?{action:"test"}:{})};const r=await fetch("/api/internal/sources",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const j=await r.json();setMessage(r.ok?(mode==="test"?`Valid feed: ${j.data.itemCount} parseable items. Source was not activated.`:"Source added as pending review."):j.error?.message);if(r.ok&&mode==="add")load();}
async function setStatus(id:string,status:string){await fetch("/api/internal/sources",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status})});load();}
return <><PageHeader mode="admin" title="Sources" description="Approve, test, and operate RSS and Atom feeds"/><div className="page-grid"><Panel title="Private MVP session"><div style={{padding:15,display:"flex",gap:8,flexWrap:"wrap"}}><button onClick={load} style={button}>Load sources</button><span className="muted" style={{fontSize:10,alignSelf:"center"}}>Access is protected by an HTTP-only session cookie.</span></div></Panel><Panel title="Add or test a source"><div style={{padding:15,display:"grid",gridTemplateColumns:"1fr 2fr auto auto",gap:8}}><input aria-label="Source name" value={name} onChange={e=>setName(e.target.value)} placeholder="Source name" style={input}/><input aria-label="Feed URL" value={feedUrl} onChange={e=>setFeedUrl(e.target.value)} placeholder="https://publisher.example/feed.xml" style={input}/><button onClick={()=>action("test")} style={button}>Test only</button><button onClick={()=>action("add")} style={button}>Add pending</button></div><p className="muted" role="status" style={{padding:"0 15px 15px",fontSize:10}}>{message}</p></Panel><Panel title="Source inventory"><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:10}}><thead><tr>{["Source","Type","Status","Refresh","Last success","Failures","Actions"].map(x=><th key={x} style={th}>{x}</th>)}</tr></thead><tbody>{sources.map(s=><tr key={s.id}><td style={td}><strong>{s.name}</strong><div className="muted">{s.feedUrl}</div></td><td style={td}>{s.feedType}</td><td style={td}>{s.status}</td><td style={td}>{s.minimumRefreshIntervalMinutes}m</td><td style={td}>{s.lastSuccessfulRefreshAt?new Date(s.lastSuccessfulRefreshAt).toLocaleString():"Never"}</td><td style={td}>{s.consecutiveFailureCount}</td><td style={td}>{["ACTIVE","PAUSED","REJECTED"].map(x=><button key={x} onClick={()=>setStatus(s.id,x)} style={{...button,marginRight:5}}>{x.toLowerCase()}</button>)}</td></tr>)}</tbody></table></div></Panel></div></>}
const input={background:"#08131e",border:"1px solid #29445d",borderRadius:5,color:"#f5f8fc",padding:"9px 10px",fontSize:10,minWidth:180};const button={background:"#123d68",border:"1px solid #256399",borderRadius:5,color:"#e8f5ff",padding:"8px 10px",fontSize:9,cursor:"pointer"};const th={padding:12,textAlign:"left" as const,color:"#90a4b8",borderBottom:"1px solid #23384f"};const td={padding:12,borderBottom:"1px solid rgba(35,56,79,.55)",verticalAlign:"top" as const};
